python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ORG_ID
python general_request_chatbot.py --model_version gpt-4-0613  --amr_cot --org_id OPENAI_ZhijingPersonal_ID
